# Algar CRM CDC Sync - Config

# Salesforce ORG ARQUITETURA (arqevery sandbox)
sf.username=alberto.bottaro@aircompany.ai.arqevery
sf.password=Nicework@0001
sf.securityToken=bpQwYa7Yk0LdA6VVtkvEI5WBJ
sf.loginUrl=https://test.salesforce.com
sf.instanceHost=algartelecommartech005--arqevery.sandbox.my.salesforce.com

# Snowflake V2
snowflake.account=vdc35898.us-east-1
snowflake.username=ALBERTOBNETO
snowflake.password=AlgarAlberto2026sf!
snowflake.warehouse=COMPUTE_WH
snowflake.database=ALGAR_CRM_LAKE
snowflake.schema=PUBLIC

# HTTP Listener
http.port=8081
